config/routes.rb
Rails.application.routes.draw do
root 'posts#index', as: 'home'



get 'about' => 'pages#about', as: 'about'

resources :posts do
    resources :comments
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :username, presence: true, length: {minimum: 1}
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    # http_basic_authenticate_with name: "admin", password: "123"

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)

        redirect_to post_path(@post)
    end

    private def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

app/controllers/not_found_controller.rb
class NotFoundController < ApplicationController
    def not_found

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @heading = "Кажись это страничка о нас лол кек"
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    http_basic_authenticate_with name: "admin", password: "123", 
    except: [:index, :show]


    def index
        @post = Post.all
    end

    def new
        @post = Post.new
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def destroy
        @post = Post.find(params[:id])

        @post.destroy
        redirect_to posts_path
    end

    def update
        @post = Post.find(params[:id])

        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end

    def create
        # render plain: params[:post].inspect

        @post =  Post.new(post_params)

        if(@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end

    private def post_params
        params.require(:post).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/not_found_helper.rb
module NotFoundHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head >
    <title>Firstblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>


    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-dark text-light border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-bold" color="white">Pizzazombie's Blog</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <span class="p-2 text-white bg-dark" ><%= link_to "Блог", home_path %></span>
    <span class="p-2 text-dark" ><%= link_to "Обо мне", about_path %></span> 
    <%# <a class="p-2 text-dark" href="#">Enterprise</a>
    <a class="p-2 text-dark" href="#">Support</a>
    <a class="p-2 text-dark" href="#">Pricing</a> %>
  </nav>
  <span class="p-2 text-dark" ><%= link_to "Новая статья", new_post_path %></span>
</div>
    <div class="container">

    <%= yield %>

    </div>
  </body>
</html>

app/views/pages/about.html.erb
<%# <h4><%= @heading %></h4>
<h4>Привет, меня зовут Лев</h4><hr>
<%# Привет! Меня зовут Лев.<br> %>
<svg class="bi bi-file-earmark-code" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M4 1h5v1H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V6h1v7a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2z"/>
  <path d="M9 4.5V1l5 5h-3.5A1.5 1.5 0 0 1 9 4.5z"/>
  <path fill-rule="evenodd" d="M8.646 6.646a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1 0 .708l-2 2a.5.5 0 0 1-.708-.708L10.293 9 8.646 7.354a.5.5 0 0 1 0-.708zm-1.292 0a.5.5 0 0 0-.708 0l-2 2a.5.5 0 0 0 0 .708l2 2a.5.5 0 0 0 .708-.708L5.707 9l1.647-1.646a.5.5 0 0 0 0-.708z"/>
</svg>
  Я программирую: 
<small class="text-muted">С/С++, PHP, HTML/CSS, PYTHON и RUBY (в частности этот блог сделан с помощью Ruby on Rails)</small>
<br><br>
<svg class="bi bi-music-note-beamed" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 13c0 1.105-1.12 2-2.5 2S1 14.105 1 13c0-1.104 1.12-2 2.5-2s2.5.896 2.5 2zm9-2c0 1.105-1.12 2-2.5 2s-2.5-.895-2.5-2 1.12-2 2.5-2 2.5.895 2.5 2z"/>
  <path fill-rule="evenodd" d="M14 11V2h1v9h-1zM6 3v10H5V3h1z"/>
  <path d="M5 2.905a1 1 0 0 1 .9-.995l8-.8a1 1 0 0 1 1.1.995V3L5 4V2.905z"/>
</svg>
  Я делаю музыку:
 <small class="text-muted">electronic(IDM, Synth-pop), Downtempo(Acid house, Ambient) и Alternative dance</small>
<br><br>
<svg class="bi bi-camera-video" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M2.667 3.5c-.645 0-1.167.522-1.167 1.167v6.666c0 .645.522 1.167 1.167 1.167h6.666c.645 0 1.167-.522 1.167-1.167V4.667c0-.645-.522-1.167-1.167-1.167H2.667zM.5 4.667C.5 3.47 1.47 2.5 2.667 2.5h6.666c1.197 0 2.167.97 2.167 2.167v6.666c0 1.197-.97 2.167-2.167 2.167H2.667A2.167 2.167 0 0 1 .5 11.333V4.667z"/>
  <path fill-rule="evenodd" d="M11.25 5.65l2.768-1.605a.318.318 0 0 1 .482.263v7.384c0 .228-.26.393-.482.264l-2.767-1.605-.502.865 2.767 1.605c.859.498 1.984-.095 1.984-1.129V4.308c0-1.033-1.125-1.626-1.984-1.128L10.75 4.785l.502.865z"/>
</svg>
  Я делаю художественные видео:<small class="text-muted"> снимаю (sony, gopro) и монтирую (Davinchi Resolve, Adobe Premier, After Effect)</small>
<br><br>
<a href="https://pizzazombie.me/">Контакты</a>

app/views/posts/edit.html.erb
<h2>Редактирование поста</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
    <% end %>
<% end %>
<p>
    Какое-то название<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
    текст статьи<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
    <br>
    <%= f.submit({:class => 'btn btn-success'})  %>
</p>
<% end %>

app/views/posts/index.html.erb
<h1>Все записи</h1>
<hr>
<% @post.each do |post| %>

    <div class="alert alert-light">
        <h3>
            <%= post.title %>
        </h3>
        <p>
            <%= post.body %>
        </p>

        <%= link_to "Читать полностью", post_path(post), :class => 'btn btn-outline-dark btn-sm'%>

        </div>
<% end %>

app/views/posts/new.html.erb
<h2>Добавить новую статью</h2>
<%= form_for :post, url: posts_path do |f| %>

<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
    <% end %>
<% end %>
<p>
    Название статьи<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
    Текст статьи<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
    <br>
    <%= f.submit({:class => 'btn btn-success'})  %>
</p>
<% end %>

app/views/posts/show.html.erb
<h1>
<%= @post.title%>

</h1>
<p>
<%= @post.body%>

</p>
<%# <hr> %>

<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning btn-sm' %>
<%= link_to "Удалить пост",  post_path(@post), method: :delete, 
data: {confirm: "Уверены в удалении статьи?"}, :class => 'btn btn-danger btn-sm' %>
<hr>

<h4>Все комментарии</h4>
<% @post.comments.each do |comment| %>

    <div class="alert alert-light">
      <p><strong><%= comment.username %>: <%= comment.body%></strong>
      </p>
        </div>
<% end %>

<hr>
<%# секция комментариев %>

<h4>Комментировать</h4>
<%= form_for([@post, @post.comments.build]) do |f| %>

<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
    <% end %>
<% end %>
<p>
    Пользователь<br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
</p>
<p>
    текст комментария<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
    <br>
    <%= f.submit("добавить ", {:class => 'btn btn-warning'})  %>
</p>
<% end %>